# Generated by Django 5.1.7 on 2025-04-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_guardian_class_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='matter_choices',
            field=models.CharField(choices=[('CH', 'Ciencias Humanas'), ('L', 'Linguagens'), ('M', 'Matematica'), ('CN', 'Ciencias da Natureza'), ('DS', 'Desenvolvimento de sistemas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='matter_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_matter', to='school.class', verbose_name="Student's matter"),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_choices',
            field=models.CharField(choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='itinerary_choices',
            field=models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=50, null=True),
        ),
    ]
