# Generated by Django 5.1.7 on 2025-04-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_class_matter_choices_professor_matter_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_choices', models.CharField(choices=[('CH', 'Ciencias Humanas'), ('L', 'Linguagens'), ('M', 'Matematica'), ('CN', 'Ciencias da Natureza')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='matter_choices',
        ),
        migrations.AlterField(
            model_name='professor',
            name='matter_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_matter', to='school.matter', verbose_name="Student's matter"),
        ),
    ]
