# Generated by Django 5.1.7 on 2025-04-23 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_matter_remove_class_matter_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
