# Generated by Django 5.1.7 on 2025-04-23 14:36

import django.db.models.deletion
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_contract_uploaded_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_presence', models.FloatField(default=0, validators=[school.validators.validate_nota], verbose_name='Grade of Presence')),
                ('grade_activity', models.FloatField(default=0, validators=[school.validators.validate_nota], verbose_name='Grade of Activity')),
                ('grade_evaluative', models.FloatField(default=0, validators=[school.validators.validate_nota], verbose_name='Grade of Evaluative')),
                ('grade_final', models.FloatField(default=0, editable=False, validators=[school.validators.validate_nota], verbose_name='Final Grade')),
                ('classs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_class', to='school.class', verbose_name='class')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_matter', to='school.matter', verbose_name='matter')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='school.student', verbose_name='student')),
            ],
            options={
                'unique_together': {('student', 'classs', 'matter')},
            },
        ),
    ]
